import "./globals.css";
import Image from "next/image";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Woovi Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="flex justify-center my-9 ">
          <Image
            src="/LogoWoovi.svg"
            alt="logo da empresa woovi"
            width={123}
            height={36}
          />
        </div>
        {children}
        <Box className="flex justify-center items-end relative">
            <footer className="flex my-12 space-x-1 ">
              <Image
                src="/icon-security.svg"
                alt="icone seguro"
                width={16}
                height={18}
              />
              <Typography variant="body1" style={{ color: '#B2B2B2' }}>
                Pagamento 100% seguro via:
              </Typography>
              <Image
                src="/Logo-Woovi-Gray.svg"
                alt="logo da empresa woovi"
                width={57}
                height={17}
              />
            </footer>
        </Box>
      </body>
    </html>
  );
}
